### PR TITLE
Header/Active merchants redesign

### PR DESCRIPTION
**Pull request by user1736**
Hey @Xeio ! After some trial and error process we managed to put some visual adjustments together. 

New header and controls:
image

Empty merchant card
image

Card fan
image

### CODE REVIEW

**Comment by Xeio** [comment]
Looks great. 

I noticed the submit location button causes the whole page to reload which is a bit ugly for Blazor (having to re-auth and everything). I'm assuming I can just tweak the button to be a link rather than setting the window location through JS to fix.

Also something a little bit wonky about the popover for multi-submissions, seems like the votes aren't always causing the overlay to re-render (I'm guessing just needs an extra StateChanged call somewhere). The main page behind the overlay immediately updates though so that's working well. :)

I'll take a look into the code changes a bit more in-depth when I get a chance.

**Comment by Xeio** [comment]
Deployed to test.lostmerchants.com. Will probably deploy it live some time tomorrow when I'm less sleepy.

**Comment by user1736** [comment]
@Xeio hey! I finally got time to get back to this PR. If space is the question, I think it's better to use the toggle to switch between the old table view and a new card one, so people can pick the one that's more useful to them, since cards aren't designed to be space efficient much 😅  

I'll try to figure out something for timer view/placement and a simplified table view, so it can also be applied to the upcoming merchants' section.

**Comment by Xeio** [comment]
Hmmmm, not sure about formatting tools, generally the VS defaults are 4-space indents, and auto-convert of tabs to spaces. I mostly like the VS/Microsoft style defaults which is why I use them.

If you want to make another pull request to do further tweaking I wouldn't generally be opposed. Mostly I've made tweaks as I went to the card spacing. Some of it's simpler stuff like just changing the color of cards that don't have a submission yet, and then there's some more spacing changes like I collapse most of the "empty" spacing between cards unless there is a secondary/teriary merchant for that particular card that needs shown.

It's all deployed to the live site as well at this point if you want to look at it. I don't really have anything currently in the pipeline as far as UI changes, though I'll probably play around with a few things whenever I get in the mood.

**Comment by user1736** [comment]
Yeah, I'll try to sketch something on the weekend for a compact view, as I assume that's the most contested point :)

**Comment by Xeio** [comment]
Oof, figured out why the overlay was taking so long to render, it was waiting for a timer-tick. 😅

Now it's instant and feels so much nicer.

**Pull request merged**
