### PR TITLE
Android app

### PR DESCRIPTION
**Pull request by Xeio**
Semi-experimental, mostly needs some UI touchups though functionality is all working

### CODE REVIEW

**Comment by Morph21** [comment]
Hi would you be able to write a simple instruction about how to build that app into apk file?

**Comment by Xeio** [comment]
My plan is to do that once I'm done with it, the required changes are even deployed to the non-test version of the site yet so the app by itself won't do anything.

I've been busy with Valtan. 😵

**Comment by Morph21** [comment]
ok, thanks for info

**Comment by Xeio** [comment]
See here https://github.com/Xeio/WanderLost/releases

**Comment by Morph21** [comment]
I thought it would have notifications for merchants but I guess it will come later on? Atm it's only for wei card and leggendary rapport?

**Pull request merged**
