### PR TITLE
Added option to report false location/card/item and suggest replacement

### PR DESCRIPTION
**Pull request by Cyco0815**
Added support for multiple instances of the same merchant with different location/card/item. To keep it organized, I added a "Votes" counter to each ActiveMerchant so users are able to detect the correct entry. Votes for a merchant are only increased when an identical merchant is suggested via the form, a simple upvote/downvote button would invite too many trolls I think...

Grouped ActiveMerchants under ActiveMerchantGroups to support these multiple instances. On merchant expiry all suggestions are reset and only one instance of each merchant stays.

### CODE REVIEW

**Comment by Xeio** [comment]
Looks like a cool way to handle bad info.

So from running this, currently the only way to add a vote is to "suggest replacement" and then submit the same information again?

**Comment by Cyco0815** [comment]
Exactly.
I thought about a more sophisticated voting mechanism but since there are no user accounts, it's a bit hard to limit the votes per user, as they are only differentiated by the SignalR ConnectionId. I guess you could store a UserId in the BlazoredStorage/Cookies to help with that, but that requires some additional setup in the Client-Server communication.

**Comment by Xeio** [comment]
Makes sense. Yeah I'm leaning towards adding at least a very simple IP-based check, maybe an account system later, though I don't really think I'd ever want to try and force an account just to submit data anyway.

**Comment by Xeio** [comment]
I think I'm going to temporarily pull this into its own branch, I think it makes sense to tweak some things like moving some of the Expire Dates onto the "group" and then just have a possibly-empty list of instances.

Also may go in and fix few a few oddities like giving the group an instance of its own static data, which I probably should have done originally and just set so it doesn't get serialized.

**Pull request merged**
